In [7]:
import torch
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
import torch.nn as nn

# device and cuda

In [25]:
torch.cuda.is_available()
torch.cuda.current_device()
torch.tensor([1])
torch.tensor([1]).cuda()

True

0

tensor([1])

tensor([1], device='cuda:0')

In [26]:
torch.cuda.set_device(2)
torch.cuda.current_device()
x = torch.tensor([1]).cuda()
x

2

tensor([1], device='cuda:2')

In [27]:
# function to is often used
device = torch.device('cuda:1')
x.to(device)

tensor([1], device='cuda:1')

In [ ]:
#torch.nn.Module is the constructed model
# device can also be given a number like device = 2
torch.nn.Module.cuda(device = device )

In [ ]:
tensor = torch.randn(2,device = device)


# tensor.cuda return a copy and the same as tensor.to
tensor = torch.randn(2)
tensor = tensor.cuda(device = device)

# tensor

## create

In [ ]:
# if has known tensors data(array like)
torch.tensor([1,2,3])
torch.tensor([1,2.1,3])
torch.tensor([1,2,3],dtype=torch.int)
torch.IntTensor([1,2,3])
torch.FloatTensor([1,2,3])
torch.Tensor([1,2,])
# from numpy
a = np.array([1,2,3])
torch.from_numpy(a)

In [ ]:
# if we don't want data 
torch.zeros(2,3)
a = torch.zeros((2,3),dtype=torch.int)
a
torch.zeros_like(a,dtype=torch.float)
# the same for torch.ones

In [ ]:
torch.full((2,3),3.1415)
torch.full_like(a,3.1415)
torch.rand((2,3))
torch.rand_like(a,dtype=torch.float)
# 正太分布，零均值 方差为1
torch.randn((2,3))
torch.randn_like(a,dtype=torch.float)
# 限定范围随机
torch.randint(2,8,(2,3))
torch.randint_like(a,2,8)

# joining slicing demention

### advanced indexing

In [8]:
# for lstm variable length input to select the last output of lstm according to the input length

x = torch.randint(0,100,(5,4,3))
length = torch.tensor([2,1,2,1,1],dtype=torch.long)
x,length
x[torch.arange(x.size(0)),length -1]

(tensor([[[ 0., 82., 51.],
          [64., 33., 28.],
          [48., 43., 16.],
          [34., 92., 99.]],
 
         [[78.,  2.,  1.],
          [51., 61., 68.],
          [62., 59.,  4.],
          [11., 43., 30.]],
 
         [[90., 10.,  7.],
          [26., 92., 91.],
          [75., 32., 32.],
          [47., 30.,  5.]],
 
         [[28., 61., 80.],
          [81., 42., 20.],
          [ 0., 68., 82.],
          [58., 79., 98.]],
 
         [[14.,  7.,  7.],
          [ 2., 11., 41.],
          [19., 45., 32.],
          [39., 39., 31.]]]), tensor([2, 1, 2, 1, 1]))

tensor([[64., 33., 28.],
        [78.,  2.,  1.],
        [26., 92., 91.],
        [28., 61., 80.],
        [14.,  7.,  7.]])

### get mask by input length

In [10]:
torch.arange(4)
torch.arange(4).expand(*length.shape,4)
mask = torch.arange(4).expand(*length.shape,4)< length.unsqueeze(1)
mask
x,torch.mul(x,mask.float().unsqueeze(-1))

tensor([0, 1, 2, 3])

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])

tensor([[1, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0]], dtype=torch.uint8)

(tensor([[[ 0., 82., 51.],
          [64., 33., 28.],
          [48., 43., 16.],
          [34., 92., 99.]],
 
         [[78.,  2.,  1.],
          [51., 61., 68.],
          [62., 59.,  4.],
          [11., 43., 30.]],
 
         [[90., 10.,  7.],
          [26., 92., 91.],
          [75., 32., 32.],
          [47., 30.,  5.]],
 
         [[28., 61., 80.],
          [81., 42., 20.],
          [ 0., 68., 82.],
          [58., 79., 98.]],
 
         [[14.,  7.,  7.],
          [ 2., 11., 41.],
          [19., 45., 32.],
          [39., 39., 31.]]]), tensor([[[ 0., 82., 51.],
          [64., 33., 28.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]],
 
         [[78.,  2.,  1.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]],
 
         [[90., 10.,  7.],
          [26., 92., 91.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]],
 
         [[28., 61., 80.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]],
 
  

### reverse input

In [ ]:
batch_size, seq_len, word_dim = x.size()
inv_idx = torch.arange(seq_len - 1, -1, -1).long()
inv_idx = inv_idx.unsqueeze(0).unsqueeze(-1).expand_as(x)
inv_idx
'--------------------'
shift_idx = torch.arange(0, seq_len).long()
shift_idx = shift_idx.unsqueeze(0).unsqueeze(-1).expand_as(x)
shift = (seq_len + (-1 * length)).unsqueeze(-1).unsqueeze(-1).expand_as(x)
shift_idx = shift_idx + shift
shift_idx = shift_idx.clamp(0, seq_len - 1)
shift_idx

x.gather(1, inv_idx)
x.gather(1, inv_idx).gather(1, shift_idx)

## merger

In [ ]:
x = torch.range(1,6).view(2,3)
y = torch.range(6,11).view(2,3)
x
y
torch.cat((x,y),0)
torch.cat((x,y),1)



torch.stack((x,y),0)
torch.stack((x,y),1)
torch.stack((x,y),2)


## change demention

In [ ]:
a = torch.range(0,11)
a
a.reshape(4,3)
# view 在操作不连续的tensor之前需要先 continues(),而reshape 是不需要的，reshape 是后来版本新实现的，建议用reshape
'b:'
b = a.view(6,2)
b

# repeat 这个函数比较复杂
'#########repeat###########'
x = torch.randn(2,3)
x,x.shape
x.repeat(2,1).shape
x.repeat(1,2).shape
x.repeat(2,2).shape
x.repeat(5,2,2).shape   # 如果repeat的参数比tensor的shape多，则将参数中的个数从后面减去tensor的shape个数，
                        # 将tensor视为一个整体，复制参数中剩余的位数（位数从右向左看）
x.repeat(6,5,1,1).shape

x = torch.randn((32,50))
x.repeat(20,1,1) == x.unsqueeze(0).repeat(20,1,1)

## 转置

In [ ]:
a = torch.randn((2,4,6))
a.shape
a.transpose(0,1).shape
a.permute(1,2,0).shape   # 新的从旧的中获取

## squeeze

In [ ]:
a = torch.randn((2,1,4))
a.shape
a.squeeze(1).shape
a.unsqueeze(1).shape

# math operation

## operator

In [ ]:
a = torch.range(0,2)
b = torch.range(3,5)
a,b

In [ ]:
a + b
a - b
a * b
a / b

# for nn


## Bilinear to calculate h^t * W * h

In [ ]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.line1 = nn.Linear(20, 10)# submodule: Conv2d
        self.conv1 = nn.Conv1d(20, 20, 5)
        self.rnn = nn.LSTM(300,300)

    def forward(self, x):
       x = F.relu(self.conv1(x))
       return F.relu(self.conv1(x))

## 查看模型总的参数量

In [ ]:
m = Model()

In [ ]:
total = 0
for i in m.parameters():
    total += i.numel()
total

### 模型参数拷贝

In [ ]:
# model parameters 
m.state_dict()

m2 = Model()
m2.load_state_dict(m.state_dict())
# now m and m2 have the same parameters

## nn.module模块

In [ ]:
m
m.line1

In [ ]:
m.modules()
'#############################'
for i in m.modules():
    print(i)
'---------------------------------------'
for i in m.named_modules():
    print(i)

In [ ]:
for i in m.children():
    print(i)
'-------------------------------'
for i in m.named_children():
    print(i)

In [ ]:
for i in m.parameters():
    print(i.shape,'\t',type(i),'\t',type(i.data))
'--------------------------------------------'
for i in m.named_parameters():
    print(type(i),'\t',i[0],'\t',i[1].shape)


In [ ]:
m.state_dict()
'---------------------------'
m.state_dict().keys()

In [ ]:

B = nn.Bilinear(2, 2, 1)
x_ones = torch.ones(2)
x_zeros = torch.zeros(2)
B(x_ones, x_zeros)

In [ ]:
c = nn.Bilinear(10, 20, 40)
c.weight.shape

## cnn
out channel is the number of kenels

## linear convolution

In [ ]:

oc = torch.nn.Conv1d(300,2,3)

oc
oc.state_dict().keys()
oc.weight.shape

x = torch.randn((32,300,23))
y = oc(x)

y.shape

In [ ]:
mx = torch.nn.MaxPool1d(21)
z = mx(y)
z.shape
z = z.squeeze(2)
z.shape

## 2d convolution

In [ ]:
tc = torch.nn.Conv2d(1,2,3,padding=1)
x = torch.randn(32,23,300).unsqueeze(1)
x.shape
y = tc(x)
y.shape

In [ ]:
w = torch.Tensor(3, 5)
w

In [ ]:
x = torch.rand(5)

In [ ]:
x

In [ ]:
inv_idx = torch.arange(x.size(0)-1, -1, -1).long()

In [ ]:
inv_idx

In [ ]:
inv_tensor = x.index_select(0, inv_idx)
inv_tensor

### usage
实现了变长的lstm，验证了与原生的lstm的一致性
注： c_n 不一样，没有特殊处理，没关注c_n

In [ ]:
lstm = nn.LSTM(2,1,num_layers=2,batch_first=True)

In [ ]:
inputs = torch.randn(4,5,2)
length = torch.tensor([5,4,3,2]).long()

In [ ]:
batch_x_pack = torch.nn.utils.rnn.pack_padded_sequence(inputs,length,batch_first=True)
packed,(h_n,c_n) = lstm(batch_x_pack)
lstm_out,out_len = torch.nn.utils.rnn.pad_packed_sequence(packed,batch_first=True)

In [ ]:
class LSTM_Mask(nn.Module):
    def __init__(self,input_size,hidden_size,num_layers=1,batch_first=False):
        super(LSTM_Mask,self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.batch_first = batch_first
        self.lstm = nn.LSTM(input_size,hidden_size,num_layers,batch_first=True)
    
    def get_mask(self,length,max_len):
        # length torch.tensor or torch.cuda.tensor [*,b]
        if length.is_cuda:
            mask = torch.arange(max_len).expand(*length.shape,max_len).to(length.device) < length.unsqueeze(1)
        else:
            mask = torch.arange(max_len).expand(*length.shape,max_len) < length.unsqueeze(1)
        mask = mask.float()
        return mask
    
    def forward(self,inputs,length):
        # inputs [b,s,dim] or [s,b,dim]
        # length [b,l] 
        if self.batch_first is False:
            inputs = inputs.transpose(0,1)
        lstm_out, (h_n,c_n) = self.lstm(inputs)
        mask = self.get_mask(length,lstm_out.size(1))
        lstm_out_masked = torch.mul(lstm_out,mask.unsqueeze(-1))
        h_n_temp = []
        
        h_n_temp = lstm_out_masked[torch.arange(lstm_out_masked.size(0)).to(lstm_out_masked.device),length-1]
#         for i,data in enumerate(lstm_out_masked):
#             h_n_temp.append(data[length[i]-1])
#         h_n_temp = torch.stack(h_n_temp)
        h_n = h_n_temp
        if self.batch_first is False:
            lstm_out_masked = lstm_out_masked.transpose(0,1)
        h_n = h_n.unsqueeze(0)
        return lstm_out_masked, (h_n,c_n)

In [ ]:
lstm_self = LSTM_Mask(2,1,num_layers=2,batch_first=True)

In [ ]:
lstm_self.lstm.load_state_dict(lstm.state_dict())

In [ ]:
out_self,(h_s,c_s) = lstm_self(inputs,length)

In [ ]:
torch.equal(out_self,lstm_out)

## 实现了双向lstm

In [ ]:
class biLSTM_Mask(nn.Module):
    def __init__(self,input_size,hidden_size,num_layers=1,batch_first=False):
        super(biLSTM_Mask,self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.batch_first = batch_first
        self.fd_lstm = nn.LSTM(input_size,hidden_size,num_layers,batch_first=True)
        self.bd_lstm = nn.LSTM(input_size,hidden_size,num_layers,batch_first=True)
    
    def get_mask(self,length,max_len):
        # length torch.tensor or torch.cuda.tensor [*,b]
        
        if length.is_cuda:
            mask = torch.arange(max_len).expand(*length.shape,max_len).to(length.device) < length.unsqueeze(1)
        else:
            mask = torch.arange(max_len).expand(*length.shape,max_len) < length.unsqueeze(1)
        mask = mask.float()
        return mask
    
    def reverse_sequence(self, x, x_lens):
        batch_size, seq_len, word_dim = x.size()

        inv_idx = torch.arange(seq_len - 1, -1, -1).long()
        shift_idx = torch.arange(0, seq_len).long()

        if x.is_cuda:
            inv_idx = inv_idx.cuda(x.get_device())
            shift_idx = shift_idx.cuda(x.get_device())

        inv_idx = inv_idx.unsqueeze(0).unsqueeze(-1).expand_as(x)
        shift_idx = shift_idx.unsqueeze(0).unsqueeze(-1).expand_as(x)
        shift = (seq_len + (-1 * x_lens)).unsqueeze(-1).unsqueeze(-1).expand_as(x)
        shift_idx = shift_idx + shift
        shift_idx = shift_idx.clamp(0, seq_len - 1)

        x = x.gather(1, inv_idx)
        x = x.gather(1, shift_idx)

        return x 
    
    
    def forward(self,inputs,length):
        # inputs [b,s,dim] or [s,b,dim]
        # length [b] 
        if self.batch_first is False:
            inputs = inputs.transpose(0,1)
        ivs_inputs = inputs
        ivs_inputs = self.reverse_sequence(inputs,length)
        
        fd_lstm_out, (fd_h_n,fd_c_n) = self.fd_lstm(inputs)
        bd_lstm_out, (bd_h_n,bd_c_n) = self.bd_lstm(ivs_inputs)
        fd_mask = self.get_mask(length,fd_lstm_out.size(1))
        bd_mask = self.get_mask(length,bd_lstm_out.size(1))
        
        fd_lstm_out_masked = torch.mul(fd_lstm_out,fd_mask.unsqueeze(-1))
        bd_lstm_out = self.reverse_sequence(bd_lstm_out,length)
        bd_lstm_out_masked = torch.mul(bd_lstm_out,bd_mask.unsqueeze(-1))
        
        
        
        full_out = torch.cat((fd_lstm_out_masked,bd_lstm_out_masked),dim=2)
        
        
#         h_n_f = []
#         for i,data in enumerate(fd_lstm_out_masked):
#             h_n_f.append(data[length[i]-1])
#         h_n_f = torch.stack(h_n_f)
        
        h_n_f = fd_lstm_out_masked[torch.arange(fd_lstm_out_masked.size(0)).to(fd_lstm_out_masked.device),length-1]
        
        
#         h_n_b = []
#         for i,data in enumerate(bd_lstm_out_masked):
#             h_n_b.append(data[0])
#         h_n_b = torch.stack(h_n_b)
        h_n_b = bd_lstm_out_masked[torch.arange(bd_lstm_out_masked.size(0)).to(bd_lstm_out_masked.device),0]
        
        
        
        h_n = torch.stack((h_n_f,h_n_b))
        

        if self.batch_first is False:
            full_out = full_out.transpose(0,1)
        return full_out, (h_n,0)

In [ ]:
bilstm = nn.LSTM(2,1,batch_first=True,bidirectional=True)
bilstm_self = biLSTM_Mask(2,1,batch_first=True)

In [ ]:
for i in bilstm.named_parameters():
    print(type(i),'\t',i[0],'\t',i[1].shape)

In [ ]:
bilstm_self.fd_lstm.weight_ih_l0 = bilstm.weight_ih_l0
bilstm_self.fd_lstm.weight_hh_l0 = bilstm.weight_hh_l0
bilstm_self.fd_lstm.bias_ih_l0 = bilstm.bias_ih_l0
bilstm_self.fd_lstm.bias_hh_l0 = bilstm.bias_hh_l0

bilstm_self.bd_lstm.weight_ih_l0 = bilstm.weight_ih_l0_reverse
bilstm_self.bd_lstm.weight_hh_l0 = bilstm.weight_hh_l0_reverse
bilstm_self.bd_lstm.bias_ih_l0 = bilstm.bias_ih_l0_reverse
bilstm_self.bd_lstm.bias_hh_l0 = bilstm.bias_hh_l0_reverse

In [ ]:
bibatch_x_pack = torch.nn.utils.rnn.pack_padded_sequence(inputs,length,batch_first=True)
bipacked,(h_n,c_n) = bilstm(bibatch_x_pack)
bilstm_out,out_len = torch.nn.utils.rnn.pad_packed_sequence(bipacked,batch_first=True)

In [ ]:
biout_self,(h_s,c_s) = bilstm_self(inputs,length)

In [ ]:
torch.equal(biout_self,bilstm_out)

In [ ]:
torch.equal(h_n,h_s)

In [ ]:
# 在有pad长度的attention时候，虽然乘出来是0，但是0经过softmax之后并不是0
# 针对这个现象，要做mask，做法很简单，就是在需要mask的地方加上一个很小的负数，不mask的地方加0就行
import torch.nn.functional as F
temp = torch.tensor([1,2,3,0,0,0]).float()
mask = torch.tensor([0,0,0,-100000,-100000,-100000]).float()
temp_mask = temp + mask
F.softmax(temp)
F.softmax(temp_mask)

#### shuffle data

In [11]:
r=torch.randperm(10)
r

tensor([2, 5, 0, 3, 6, 1, 7, 4, 9, 8])

## masked attention

In [ ]:
import math
class Attention_masked(nn.Module):
    def __init__(self, embed_dim, hidden_dim=None, out_dim=None, n_head=1, score_function='dot_product', dropout=0):
        ''' Attention Mechanism
        :param embed_dim:
        :param hidden_dim:
        :param out_dim:
        :param n_head: num of head (Multi-Head Attention)
        :param score_function: scaled_dot_product / mlp (concat) / bi_linear (general dot)
        :return (?, q_len, out_dim,)
        '''
        super(Attention_masked, self).__init__()
        if hidden_dim is None:
            hidden_dim = embed_dim // n_head
        if out_dim is None:
            out_dim = embed_dim
        self.embed_dim = embed_dim
        self.hidden_dim = hidden_dim
        self.n_head = n_head
        self.score_function = score_function
        self.w_k = nn.Linear(embed_dim, n_head * hidden_dim)
        self.w_q = nn.Linear(embed_dim, n_head * hidden_dim)
        self.proj = nn.Linear(n_head * hidden_dim, out_dim)
        self.dropout = nn.Dropout(dropout)
        if score_function == 'mlp':
            self.weight = nn.Parameter(torch.Tensor(hidden_dim*2))
        elif self.score_function == 'bi_linear':
            self.weight = nn.Parameter(torch.Tensor(hidden_dim, hidden_dim))
        else:  # dot_product / scaled_dot_product
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.hidden_dim)
        if self.weight is not None:
            self.weight.data.uniform_(-stdv, stdv)

    def forward(self, k, q,k_step,q_step):
        '''
        k: context
        q: target
        k_len: k length, shape [batch] (one dementional vector )，tensor
        q_len: q length, shape [batch] (one dementional vector), tensor
        '''
        if len(q.shape) == 2:  # q_len missing
            q = torch.unsqueeze(q, dim=1)
        if len(k.shape) == 2:  # k_len missing
            k = torch.unsqueeze(k, dim=1)
        mb_size = k.shape[0]  # ?
        k_len = k.shape[1]
        q_len = q.shape[1]
        mask = torch.tensor([[0]*step + [-10000]*(k_len-step) for step in k_step.numpy()],dtype=torch.float ).unsqueeze(1)
        mask = torch.cat([mask for _ in range(self.n_head)],dim=0)
        # k: (?, k_len, embed_dim,)
        # q: (?, q_len, embed_dim,)
        # kx: (n_head*?, k_len, hidden_dim)
        # qx: (n_head*?, q_len, hidden_dim)
        # score: (n_head*?, q_len, k_len,)
        # output: (?, q_len, out_dim,)
        kx = self.w_k(k).view(mb_size, k_len, self.n_head, self.hidden_dim)
        kx = kx.permute(2, 0, 1, 3).contiguous().view(-1, k_len, self.hidden_dim)
        qx = self.w_q(q).view(mb_size, q_len, self.n_head, self.hidden_dim)
        qx = qx.permute(2, 0, 1, 3).contiguous().view(-1, q_len, self.hidden_dim)
        if self.score_function == 'dot_product':
            kt = kx.permute(0, 2, 1)
            score = torch.bmm(qx, kt)
        elif self.score_function == 'scaled_dot_product':
            kt = kx.permute(0, 2, 1)
            qkt = torch.bmm(qx, kt)
            score = torch.div(qkt, math.sqrt(self.hidden_dim))
        elif self.score_function == 'mlp':
            kxx = torch.unsqueeze(kx, dim=1).expand(-1, q_len, -1, -1)
            qxx = torch.unsqueeze(qx, dim=2).expand(-1, -1, k_len, -1)
            kq = torch.cat((kxx, qxx), dim=-1)  # (n_head*?, q_len, k_len, hidden_dim*2)
            # kq = torch.unsqueeze(kx, dim=1) + torch.unsqueeze(qx, dim=2)
            score = F.tanh(torch.matmul(kq, self.weight))
        elif self.score_function == 'bi_linear':
            qw = torch.matmul(qx, self.weight)
            kt = kx.permute(0, 2, 1)
            score = torch.bmm(qw, kt)
        else:
            raise RuntimeError('invalid score_function')
        score = score + mask
        score = F.softmax(score, dim=-1)
        output = torch.bmm(score, kx)  # (n_head*?, q_len, hidden_dim)
        output = torch.cat(torch.split(output, mb_size, dim=0), dim=-1)  # (?, q_len, n_head*hidden_dim)
        output = self.proj(output)  # (?, q_len, out_dim)
        output = self.dropout(output)
        return output, score

k = torch.randn((32,23,300))
# q = torch.randn((32,300)) is also right
q = torch.randn((32,3,300))
k_step = torch.randint(0,23,(32,),dtype=torch.int)
q_step = torch.full((32,),1,dtype=torch.int)
k_len = 23

output,score  =  att(k,q,k_step,q_step)